# Stage 1 - build express app
FROM node:11 as bundle

LABEL maintainer="vashchukmaksim@gmail.com"

# Copy source
COPY . /usr/src
WORKDIR /usr/src

# Install dependencies
RUN yarn install

# Install dependencies from private registry
RUN rm -rf /root/.npmrc
RUN touch /root/.npmrc
RUN echo "registry = http://host.docker.internal:4873\n" >>  /root/.npmrc
RUN echo "ca = null\n" >>  /root/.npmrc
RUN echo "always-auth = true\n" >>  /root/.npmrc
RUN echo "//host.docker.internal:4873/:_authToken=jpicado:jpicado\n" >>  /root/.npmrc
RUN yarn config set registry "http://host.docker.internal:4873"

# Low level
RUN yarn add @scc/elm
RUN yarn add @scc/utils
RUN yarn add @scc/form
RUN yarn add @scc/notify
RUN yarn add @scc/modal
RUN yarn add @scc/api-proxy
RUN yarn add @scc/api-proxy-data

# Project specific
RUN yarn add @tg/ui
RUN yarn add @tg/api-proxy-auth
RUN yarn add @tg/api-proxy-bot
RUN yarn add @tg/api-proxy-drafts
RUN yarn add @tg/api-proxy-upload
RUN yarn add @tg/api-proxy-url-preview

# Build express app
RUN yarn prd:build-client
RUN yarn prd:build-server

# Stage 2 - Forever
FROM node:11

# Copy artifacts
COPY --from=bundle /usr/src/bundle_server /usr/src/bundle_server
COPY --from=bundle /usr/src/bundle_client /usr/src/bundle_client

# Copy package.json
COPY package.json yarn.lock* /usr/src/

WORKDIR /usr/src

RUN yarn global add forever
RUN yarn install --production=true

CMD ["forever", "bundle_server/server.js"]
