# Stage 1 - build express app
FROM node:11 as bundle

LABEL maintainer="vashchukmaksim@gmail.com"

# nexus
ARG NEXUS_PASSWORD
ENV NEXUS_PASSWORD=$NEXUS_PASSWORD

# Set registry
RUN rm -rf /root/.npmrc
RUN touch /root/.npmrc
RUN echo "@tg:registry=https://nexus.tgpost.me/repository/npm-private/\n" >>  /root/.npmrc
RUN echo "@scc:registry=https://nexus.tgpost.me/repository/npm-private/\n" >>  /root/.npmrc
RUN echo "ca = null\n" >>  /root/.npmrc
RUN echo "always-auth = true\n" >>  /root/.npmrc
RUN echo "//nexus.tgpost.me/:_authToken=ci:$NEXUS_PASSWORD\n" >>  /root/.npmrc
# RUN yarn config set registry "http://host.docker.internal:4873"

# Copy source
COPY . /usr/src
WORKDIR /usr/src

# Install dependencies
RUN yarn

# Build express app
RUN yarn prd:build-server

# Stage 2 - Forever
FROM node:11

# Copy artifacts
COPY --from=bundle /usr/src/bundle_server /usr/src/bundle_server
COPY package.json yarn.lock* /usr/src/
WORKDIR /usr/src

# Inastall
RUN yarn global add forever
RUN yarn install --production=true

# Run
CMD ["forever", "bundle_server/server.js"]
