apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}

  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}

    spec:
      containers:
      - name: ${PROJECT_NAME}
        image: eu.gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}

spec:
  selector:
    app: ${PROJECT_NAME}

  ports:
  - name: tupub-port
    port: 80
    targetPort: 3000
    protocol: TCP

  type: NodePort
