version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
    - image: circleci/node:10

    steps:
    - checkout

    - run:
        name: Install yarn
        command: 'sudo npm install -g yarn@latest'

    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "yarn.lock" }}

    - run:
        name: Add .npmrc with Nexus registry credentials
        command: |
          AUTH_TOKEN=${NPM_TOKEN}
          touch .npmrc
          echo "@tg:registry=https://nexus.tgpost.me/repository/npm-private/" >> .npmrc
          echo "//nexus.tgpost.me/repository/npm-private/:_authToken=NpmToken.${NPM_TOKEN}" >> .npmrc

    - run:
        name: Install packages
        command: yarn install --frozen-lockfile

    - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
        - ~/app/node_modules
        - ~/.cache/yarn

    - run:
        name: Build client part
        command: |
          yarn prd:build-client
          mkdir -p artifacts
          cp -R bundle_client ./artifacts

    - persist_to_workspace:
        root: artifacts
        paths:
        - bundle_client

  deploy_to_test:
    working_directory: ~/app
    docker:
    - image: circleci/python:3.7
      environment:
        DO_SPACE_CDN_ACCESS_KEY: $DO_SPACE_CDN_ACCESS_KEY
        DO_SPACE_CDN_ACCESS_KEY_SECRET: $DO_SPACE_CDN_ACCESS_KEY_SECRET
        DO_SPACES_CDN_STATIC_BUCKET: 'tgstatic'
        DO_SPACES_CDN_APP_DIRECTORY: 'public'
        DO_SPACES_CDN_LOCAL_DIRECTORY: './bundle_client'
        DO_SPACES_CDN_REGION: 'fra1'
    steps:
    - checkout

    - attach_workspace:
        at: ~/app

    - run:
       name: Download script to upload artifact to DO Spaces
       command: curl -o ~/app/upload.py https://cdn.tgpost.me/scripts/upload-to-spaces.py

    - restore_cache:
        keys:
        - dependency-cache-{{ checksum "~/app/upload.py" }}

    - run:
        name: Create venv and Install boto3
        command: |
          python3 -m venv ~/env
          source ~/env/bin/activate
          pip install boto3

    - save_cache:
        key: dependency-cache-{{ checksum "~/app/upload.py" }}
        paths:
        - ~/env

    - run:
        name: Upload artifacts to CDN
        command: |
          source ~/env/bin/activate
          python upload.py

workflows:
  version: 2
  pipeline:
    jobs:

    - build:
        context: global
        filters:
          branches:
            only:
            - master

    - deploy_to_test:
        requires:
        - build
        context: global
        filters:
          branches:
            only:
            - master
